version: '3.9'
services:
  db:
    image: postgres:13.3
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
#  app:
#    image:
#    container_name: test-app
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db